config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root "articles#index"

  namespace :api, defaults: { format: 'json' } do
    resources :articles do 
      resources :comments
    end
  end


    resources :articles do 
      resources :comments
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
    include Visible
    has_many :comments, dependent: :destroy

    has_one :picture, as: :imageable
    accepts_nested_attributes_for :picture
    
    validates :title, presence: true
    validates :body, presence: true, length: {minimum: 10}

    
    #validates :picture, presence: true


    def have_picture?
        return self.picture && self.picture.mon_image.attached?
    end


end

app/models/comment.rb
class Comment < ApplicationRecord
  include Visible
  belongs_to :article 

  validates :commenter, presence: true
  validates :body, presence: true, length: {minimum: 10}
  
end

app/models/concerns/visible.rb
module Visible
    extend ActiveSupport::Concern

    VALID_STATUSES = ['public', 'private', 'archived']
    included do
        validates :status, inclusion: { in: VALID_STATUSES }
    end

    class_methods do
        def public_count
            where(status: 'public').count
        end
    end


    def archived?
        status == 'archived'
    end
end

app/models/picture.rb
class Picture < ApplicationRecord
  belongs_to :imageable, polymorphic: true, optional: true
  has_one_attached :mon_image
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/api/articles_controller.rb
class Api::ArticlesController < ApiController

  def index
    articles = Article.all
    render json: articles
  end

  def show
    article = Article.find(params[:id])
    if article
      render json: article
    else
      render json: article.errors
    end
  end
#----------------------------------------------------
  def new 
    @article = Article.new
    @article.picture = Picture.new

  end

  def create
    article = Article.new(article_params)

    if article.save
      render json: article.to_json
    else
      render json: article.errors
    end
  end
#----------------------------------------------------

  def edit
    @article = Article.find(params[:id])
    if @article.picture.mon_image.attached?
    else
    @article.picture = Picture.new
    end
  end

  def update
    article = Article.find(params[:id])

    if article.update(article_params)
      render json: article
      #redirect_to @article
    else
      render json: article.errors, status: :unpocessable_entity
    end
  end
#----------------------------------------------------  

  def destroy
    article = Article.find(params[:id])

    article.destroy
    render json: article.to_json

  end


  private
  def article_params
    params.require(:article).permit(:title, :body, :status, picture_attributes: [:id, :mon_image])
  end




end

app/controllers/api/comments_controller.rb
class Api::CommentsController < ApiController

#before action  :getarticle



    def index
        article = Article.find(params[:article_id])
        if article
            render json: article.comments
        else
            render json: article.errors
        end
      end


    def show
        article = Article.find(params[:article_id])
        comment = article.comments.find(params[:id])
        if comment
            render json: comment
        else
            render json: comment.errors
        end
    end

    def create
        article = Article.find(params[:article_id])
        comment = article.comments.create(comment_params)
        if comment.save
            render json: comment.to_json
          else
            render json: comment.errors
          end
        
    end

    def destroy
        article = Article.find(params[:article_id])
        comment = article.comments.find(params[:id])

          if comment.destroy
            render json: comment.to_json
          else
            render json: comment.errors
          end
    end



    def update
        article = Article.find(params[:article_id])
        comment = article.comments.find(params[:id])
        if comment.update(comment_params)
          render json: comment
        else
          render json: comment.errors #, status: :unpocessable_entity
        end
    end



private
    def comment_params
        params.require(:comment).permit(:commenter, :body, :status)
    end

   # def getarticle
    #  Article.find(params[:article_id])
   # end

end

app/controllers/api_controller.rb
class ApiController < ActionController::API
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController

  before_action :authenticate_user!, except: [:index, :show]


  def index
    @articles = Article.all
  end

  def show
    @article = Article.find(params[:id])
  end
#----------------------------------------------------
  def new 
    @article = Article.new
    @article.picture = Picture.new

  end

  def create
    @article = Article.new(article_params)

    if @article.save
      redirect_to @article
    else
      @article.picture = Picture.new
      render :new
    end
  end
#----------------------------------------------------

  def edit
    @article = Article.find(params[:id])
    if @article.picture.mon_image.attached?
    else
    @article.picture = Picture.new
    end
  end

  def update
    @article = Article.find(params[:id])

    if @article.update(article_params)
      redirect_to @article
    else
      render :edit
    end
  end
#----------------------------------------------------  

  def destroy
    @article = Article.find(params[:id])
    @article.destroy
    redirect_to root_path
  end


  private
  def article_params
    params.require(:article).permit(:title, :body, :status, picture_attributes: [:id, :mon_image])
  end




end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

    before_action :authenticate_user!, only: :destroy


    def create
        @article = Article.find(params[:article_id])
        @comment = @article.comments.create(comment_params)
        redirect_to article_path(@article)
    end

    def destroy
        @article = Article.find(params[:article_id])
        @comment = @article.comments.find(params[:id])
        @comment.destroy
        redirect_to article_path(@article)
    end



private
    def comment_params
        params.require(:comment).permit(:commenter, :body, :status)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/articles/_form.html.erb
<%= form_with model: article do |form| %>
    <div> 
        <%= form.label :title %><br>
        <%= form.text_field :title %>
    </div>
    <br>
    <div> 
        <%= form.label :body %><br>
        <%= form.text_area :body %>
        <br>
        <%= form.fields_for :picture do |f| %>
            <%= f.file_field :mon_image%>

        <%end%>

    </div>
    
    <div>
        <%= form.label :status %>
        <%= form.select :status, ['public','private','archived'], selected: 'public' %>
    </div>

    <div>
        <%= form.submit %>
    </div>

        <div class="errorMessages">
        <% article.errors.full_messages.each do |message| %>
            <div> <%= message %> </div>
        <% end %>
        </div>
<% end %>

app/views/articles/edit.html.erb
<h1> Edit Article </h1>

<%= render "form", article: @article %>

app/views/articles/index.html.erb
<h1>SECTION HTML</h1>

<ul>
    <% @articles.each do |article| %>
        <% unless article.archived? %>
            <li>
                    <%= link_to article.title, article %>
            </li>
        <% end %>
    <% end %>
</ul>

<%= link_to "New Article", new_article_path %>

<hr>

<h1>SECTION API</h1>
#de l'article: 
<input id="selected_id" type="text" placeholder="article id default 6"/> <br />
#du comment: 
<input id="selected_commentID" type="text" placeholder="article id default 1"/> <br />
<hr>
<button onclick='sendData({},url_for(), "GET");' >show articles </button>
<button onclick='sendData({},url_for_comment_list(), "GET");' >show comments </button>
<button onclick='sendData({},url_for_comment_list(), "DELETE");'>delete article</button>
<br><br>
<button onclick='sendData({comment: {commenter: "commenter interface", body: "body interface", status: "public"}},url_for_comments(), "POST");'>Add comment</button>
<button onclick='sendData({comment: {commenter: "commenter interface", body: "body interface"}},url_for_comments(), "POST");'>Add comment error</button>
<br><br>
<button onclick='sendData({},url_for_comments_specific(), "GET");'>voir comment</button>
<br><br>
<button onclick='sendData({},url_for_comments_specific(), "DELETE");'>delete comment</button>

<br><br>
<hr>

<br />
Réponse de requête:
<br />
<textarea id="request" rows="25" cols="50"></textarea>
<script>

    function url_for(){
        let id = $("#selected_id").val() || 6;
        return "/api/articles";
    }

    function url_for_comment_list(){
        let id = $("#selected_id").val() || 6;
        return "/api/articles/"+id+"/comments";
    }

    function url_for_comments(){
        let id = $("#selected_id").val() || 6;
        return `/api/articles/${id}/comments/`;
    }

    function url_for_comments_specific(){
        let id = $("#selected_id").val() || 6;
        let commentid = $("#selected_commentID").val() || 1
        return `/api/articles/${id}/comments/${commentid}`;
    }


    function sendData(article, url, method){
        $.ajax({
            method: method,
            url: url,
            data: article,
            dataType: "json"
        }).done(function( msg ) {
            $('#request').val(JSON.stringify(msg));
            //console.log( msg );
        }).fail(function(xhr, msg) {

            $('#request').val('code HTTP: ' + xhr.status + '\n' + xhr.responseText);
        })
        .always(function() {
            //alert( "complete" );
        });
    }
</script>

app/views/articles/new.html.erb
<h1> New Article </h1>

<%= render "form", article: @article %>

app/views/articles/show.html.erb
<%= link_to 'logout', destroy_user_session_path, method: :delete, class:"w3-bar-item w3-button"%>

<%= link_to  "edit post", edit_article_path(@article) %>
<%= link_to  " | delete post", article_path(@article),
                               method: :delete,
                               data: { confirm: "Are you sure ?"} %>

<br><br>
<h1> <%= @article.title %> </h1>
<p> <%= @article.body %> </p>
<br><br>

<h2>comments: </h2>
<p>----------------</p>

<%= render @article.comments %>

<h2>add a comment: </h2>
<%= render "comments/form" %>


<%= @article.have_picture? ? image_tag(@article.picture.mon_image, class: "image") : "no pictures" %>

app/views/comments/_comment.html.erb
<% unless comment.archived? %>
    <p>
        <strong>commenter:</strong>
        <%= comment.commenter %>
    </p>

    <p> 
        <strong>comment:</strong>
        <%= comment.body %>
    </p>
    <p>
        <%= 
            link_to "delete comment", [comment.article, comment],
            method: :delete,
            data: {confirm: "are you sure?"} 
        %>
    </p>
    <p>----------------</p>
<% end %>

app/views/comments/_form.html.erb
<%= form_with model: [@article, @article.comments.build] do |form| %>
    <p>
        <%= form.label :commenter %> <br>
        <%= form.text_field :commenter %>
    </p>
    <p>
        <%= form.label :body %> <br>
        <%= form.text_area :body %>
    </p>

    <p>
        <%= form.label :status %>
        <%= form.select :status, ['public','private','archived'], selected: 'public' %>
    </p>

    <p>
        <%= form.submit %>
    </p>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TestProject</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>

    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
  </head>

  <body>
    <%= yield %>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
  </body>
</html>